### ISSUE TITLE
Dockerfile

### ISSUE THREAD

**Issue by MrCoast** [nikitapavets/react-ssr-ts-redux#5]
In https://github.com/nikitapavets/react-ssr-ts-redux/blob/master/Dockerfile:
1. Please set `WORKDIR` to `/var/www/html` to avoid `cd` in `RUN` and duplicating this path in `ADD`.
2. Please prefer using `COPY` over `ADD` in most cases, it's explained here https://nickjanetakis.com/blog/docker-tip-2-the-difference-between-copy-and-add-in-a-dockerile

**Comment by nikitapavets** [comment]
#7
